const ExperinceData = [
  {
    company: 'Brain Station 23 PLC',
    location: 'Dhaka, Bangladesh',
    roles: [
      {
        title: 'Software Engineer',
        startDate: 'January 2024',
        endDate: 'Present',
        duration: '4 mos',
        workMode: 'On-site',
        description: [
          'Developed scalable applications using TypeScript, React, and Next.js.',
          'Worked with various databases like Postgres, MongoDB, and Redis.',
          'Hands-on with AWS and Azure services (S3, EC2, Lambda).',
          'Experience with streaming data.',
          'Expertise in deployment and CI/CD processes.',
          'Log monitoring and alerting using Elasticsearch.',
        ],
        skills: [
          'TypeScript',
          'React',
          'Next',
          'Postgres',
          'MongoDB',
          'MySQL',
          'Redis',
          'Docker',
          'AWS',
          'Azure',
          'Elasticsearch',
          'Nest',
          'Express',
          'Node',
          'REST',
          'Socket.io',
        ],
      },
      {
        title: 'Associate Software Engineer',
        startDate: 'May 2022',
        endDate: 'January 2024',
        duration: '1 yr 9 mos',
        workMode: 'On-site',
        description: [
          'Proficiency in Agile development methodologies.',
          'Developed robust applications using Nest.js and Next.js.',
          'Experience with message queuing and Elasticsearch.',
          'Hands-on with AWS and Azure services (S3, EC2, Lambda).',
          'Expertise in deployment and CI/CD processes.',
        ],
        skills: [
          'TypeScript',
          'Python (Programming Language)',
          'React',
          'Next',
          'Postgres',
          'MongoDB',
          'MySQL',
          'Redis',
          'Docker',
          'AWS',
          'Azure',
          'Elasticsearch',
          'Nest',
          'Express',
          'Node',
          'REST',
          'Socket.io',
        ],
      },
      {
        title: 'Software Engineer Trainee',
        startDate: 'January 2022',
        endDate: 'April 2022',
        workMode: 'On-site',
        duration: '4 mos',
        description: [
          'Worked on production applications using MERN stack (MongoDB, Express.js, React.js, Node.js).',
          'Used Three.js for 3D graphics integration.',
        ],
        skills: ['Express.js', 'React.js', 'Node', 'MongoDB', 'Three.js'],
      },
    ],
  },
];

export default ExperinceData;
